spring:
  application:
    name: blog-search
  profiles:
    active: local
    include:
      - app
      - domain
      - infra
      - external
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

server:
  port: 9999

